// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhxC0-ch5ADBlOs3fBLhU_8m87fkHT0M',
    appId: '1:434624673842:web:1da0fad7afd795d64be42b',
    messagingSenderId: '434624673842',
    projectId: 'common-chat-70e0c',
    authDomain: 'common-chat-70e0c.firebaseapp.com',
    storageBucket: 'common-chat-70e0c.firebasestorage.app',
    measurementId: 'G-C1QH3R15QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcnxhO409U8aY9pEYYXCbHjUuHFn0czhM',
    appId: '1:434624673842:android:a6c0fdb23304114b4be42b',
    messagingSenderId: '434624673842',
    projectId: 'common-chat-70e0c',
    storageBucket: 'common-chat-70e0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgR-XsP8MD_C0REJXrf2-LS6j0qL2TmGQ',
    appId: '1:434624673842:ios:79a623c1d9e9bdb94be42b',
    messagingSenderId: '434624673842',
    projectId: 'common-chat-70e0c',
    storageBucket: 'common-chat-70e0c.firebasestorage.app',
    iosBundleId: 'com.example.commonAppChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgR-XsP8MD_C0REJXrf2-LS6j0qL2TmGQ',
    appId: '1:434624673842:ios:79a623c1d9e9bdb94be42b',
    messagingSenderId: '434624673842',
    projectId: 'common-chat-70e0c',
    storageBucket: 'common-chat-70e0c.firebasestorage.app',
    iosBundleId: 'com.example.commonAppChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRhxC0-ch5ADBlOs3fBLhU_8m87fkHT0M',
    appId: '1:434624673842:web:f808cd16e617de414be42b',
    messagingSenderId: '434624673842',
    projectId: 'common-chat-70e0c',
    authDomain: 'common-chat-70e0c.firebaseapp.com',
    storageBucket: 'common-chat-70e0c.firebasestorage.app',
    measurementId: 'G-49PELFETVG',
  );
}
